const axios = require("axios");
const OPENAI_RESPONSES_URL="https://api.openai.com/v1/responses";
const DEFAULT_MODEL=process.env.DIGITAL_TWIN_MODEL||"gpt-5-mini";
const CLAIM_TYPES=["fact","evidence_based_inference","confirmed_preference","assumption","unknown"];
const EPISTEMIC_AUDIT_SCHEMA={type:"object",additionalProperties:false,properties:{claims:{type:"array",maxItems:6,items:{type:"object",additionalProperties:false,properties:{claim:{type:"string"},type:{type:"string",enum:CLAIM_TYPES},support:{type:"string"},decisionImpact:{type:"string",enum:["material","supporting","none"]},validBridge:{type:"boolean"}},required:["claim","type","support","decisionImpact","validBridge"]}},unresolvedComparisons:{type:"array",maxItems:4,items:{type:"string"}},needsRevision:{type:"boolean"},revisionInstructions:{type:"array",maxItems:4,items:{type:"string"}}},required:["claims","unresolvedComparisons","needsRevision","revisionInstructions"]};
function outputText(response){if(response?.output_text)return response.output_text;const parts=[];for(const item of response?.output||[])for(const content of item?.content||[])if(content?.type==="output_text"&&content?.text)parts.push(content.text);return parts.join("\n").trim();}
function parseJson(text){return JSON.parse(String(text||"").trim().replace(/^```json\s*/i,"").replace(/```$/i,"").trim());}
function truncated(data){return data?.status==="incomplete"||data?.incomplete_details?.reason==="max_output_tokens";}
function mergeUsage(...items){const valid=items.filter(Boolean);if(!valid.length)return null;const sum=k=>valid.reduce((a,u)=>a+(Number(u?.[k])||0),0);return{input_tokens:sum("input_tokens"),output_tokens:sum("output_tokens"),total_tokens:sum("total_tokens"),input_tokens_details:{cached_tokens:valid.reduce((a,u)=>a+(Number(u?.input_tokens_details?.cached_tokens)||0),0)},output_tokens_details:{reasoning_tokens:valid.reduce((a,u)=>a+(Number(u?.output_tokens_details?.reasoning_tokens)||0),0)}};}
function compact(value,depth=0){if(value==null)return value;if(typeof value==="string")return value.length>600?`${value.slice(0,600)}…`:value;if(typeof value!=="object")return value;if(depth>=3)return Array.isArray(value)?`[${value.length} items]`:"[object omitted]";if(Array.isArray(value))return value.slice(0,10).map(v=>compact(v,depth+1));return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,compact(v,depth+1)]));}
function compactProfile(profile={}){return compact({investor_narrative:profile.investor_narrative,style:profile.style,concentration_tolerance:profile.concentration_tolerance,drawdown_tolerance:profile.drawdown_tolerance,liquidity_preference:profile.liquidity_preference,implementation_style:profile.implementation_style,convictions:profile.convictions,rules:profile.rules});}
function compactPlan(plan={}){return compact({decisionType:plan.decisionType,allocationAmountUsd:plan.allocationAmountUsd,screenedAssets:plan.screenedAssets,screeningComplete:plan.screeningComplete,researchAssets:plan.researchAssets,researchQuestion:plan.researchQuestion,screenedPortfolioCount:plan.screenedPortfolioCount});}
function portfolioRows(context={}){const p=context?.portfolio||{};if(Array.isArray(p.exposures)&&p.exposures.length)return p.exposures;if(Array.isArray(p.topExposures)&&p.topExposures.length)return p.topExposures;return[];}
function assetId(row={}){return String(row?.ticker||row?.asset||row?.symbol||row?.name||"").trim();}
function portfolioAssets(context={}){const seen=new Set(),out=[];for(const row of portfolioRows(context)){const asset=assetId(row),key=asset.toUpperCase();if(!asset||seen.has(key))continue;seen.add(key);out.push(asset);}return out;}
function compactContext(context={}){const p=context?.portfolio||{};const top=Array.isArray(p.topExposures)&&p.topExposures.length?p.topExposures:portfolioRows(context).slice(0,10);return{portfolio:{totalValueUsd:p.totalValueUsd,cryptoExposurePct:p.cryptoExposurePct,liquidityPct:p.liquidityPct,topExposures:compact(top.slice(0,10)),portfolioAssets:portfolioAssets(context)}};}
async function post(body,timeout=90000){return(await axios.post(OPENAI_RESPONSES_URL,body,{headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,"Content-Type":"application/json"},timeout})).data;}
const INVARIANTS=`Auditá contra estas invariantes generales; no agregues parches específicos por ticker:
A) ESTADO != ATRACTIVO: peso, valor, performance o ser posición principal no justifican comprar/vender ni desempatan atractivo salvo que la decisión sea explícitamente sobre exposición/riesgo.
B) FUERZA DE CONCLUSIÓN <= FUERZA DEL PUENTE: cuanto más extrema sea una asignación/ranking, más fuerte y explícito debe ser el puente comparativo soportado. Una inclinación cualitativa leve no sostiene por sí sola una diferencia extrema presentada como convicción derivada.
C) DECISIÓN PUNTUAL != REGLA FUTURA: una asignación actual no crea frecuencia DCA, tramos, timing, proporción mensual futura ni política persistente.
D) CONTEXTO CONOCIDO NO SE PIDE: si un dato existe en Perfil/Cartera/Plan/Evidencia, no se lo pidas otra vez al usuario ni afirmes que falta. Si un cálculo puede hacerse con datos presentes, no digas que necesitás que el usuario los provea.
E) COBERTURA != SEÑAL: research_now/defer/covered/uncovered sólo describe cobertura; no atractivo relativo.
F) PROVENIENCIA: números presentados como hechos, métricas, probabilidades, forecasts o thresholds deben existir explícitamente en inputs. Una asignación propuesta puede ser número nuevo sólo como JUICIO TÁCTICO, no dato ni cálculo derivado del research.
G) SCREENING != FUNDAMENTALES: screeningComplete sólo prueba consideración trazable de todos los activos, no análisis fundamental de todos.`;
async function auditDecision({draft,evidenceMatrix,currentProfile,context,plan}){
 const input=`Perfil: ${JSON.stringify(compactProfile(currentProfile))}\nCartera: ${JSON.stringify(compactContext(context))}\nPlan/screening: ${JSON.stringify(compactPlan(plan))}\nEvidencia: ${JSON.stringify(compact(evidenceMatrix||{}))}\nBorrador: ${String(draft||"").slice(0,7000)}`;
 const data=await post({model:DEFAULT_MODEL,reasoning:{effort:"low"},instructions:`Auditá epistemológicamente el borrador sin investigar ni decidir de nuevo. Revisá máximo 6 claims materiales. Clasificalos fact/evidence_based_inference/confirmed_preference/assumption/unknown y verificá puente lógico. ${INVARIANTS}\nAdemás: evidencia heterogénea no crea automáticamente escala común; unknown no es inferior; no inventes implementación; triggers específicos requieren evidencia o regla explícita. Si una conclusión excede soporte, degradala en vez de fabricar metodología. revisionInstructions sólo puede eliminar/degradar/reclasificar/separar/explicitar incertidumbre o corregir uso del contexto ya disponible; no pedir nueva investigación, modelos, probabilidades, scores, fórmulas, thresholds ni cálculos nuevos. needsRevision=true ante cualquier violación material.`,input,max_output_tokens:1800,text:{verbosity:"low",format:{type:"json_schema",name:"twin_epistemic_audit",strict:true,schema:EPISTEMIC_AUDIT_SCHEMA}},store:false});if(truncated(data))throw new Error("Digital Twin epistemic audit truncated; skipped to protect decision budget");return{audit:parseJson(outputText(data)),data};
}
async function reviseDecision({draft,audit,evidenceMatrix,currentProfile,context,plan}){if(!audit?.needsRevision)return{answer:draft,data:null};const input=`Perfil: ${JSON.stringify(compactProfile(currentProfile))}\nCartera: ${JSON.stringify(compactContext(context))}\nPlan/screening: ${JSON.stringify(compactPlan(plan))}\nEvidencia: ${JSON.stringify(compact(evidenceMatrix||{}))}\nAuditoría: ${JSON.stringify(compact(audit))}\nBorrador: ${String(draft||"").slice(0,7000)}`;const data=await post({model:DEFAULT_MODEL,reasoning:{effort:"low"},instructions:`Corregí únicamente las violaciones indicadas usando material disponible. ${INVARIANTS}\nNo investigues, no agregues hechos, no inventes metodología para salvar la conclusión. Si el puente no sostiene la magnitud de una diferencia, reducí la firmeza o la magnitud; no hace falta eliminar toda recomendación. No transformes una decisión de hoy en regla futura. No pidas datos ya presentes. No uses estado actual como atractivo. No inventes implementación. Español rioplatense, directo, máximo 450 palabras.`,input,max_output_tokens:2200,text:{verbosity:"low"},store:false});return{answer:outputText(data)||draft,data};}
async function auditAndReviseDecision(args){const{audit,data:auditData}=await auditDecision(args);const{answer,data:revisionData}=await reviseDecision({...args,audit});return{answer,audit,usage:mergeUsage(auditData?.usage,revisionData?.usage),apiRequests:1+(revisionData?1:0),model:revisionData?.model||auditData?.model||DEFAULT_MODEL,responseId:revisionData?.id||auditData?.id||null};}
module.exports={EPISTEMIC_AUDIT_SCHEMA,auditAndReviseDecision};
