const axios = require("axios");

const OPENAI_RESPONSES_URL = "https://api.openai.com/v1/responses";
const DEFAULT_MODEL = process.env.DIGITAL_TWIN_MODEL || "gpt-5-mini";
const MAX_SUBSTANTIVE_ANSWERS = 6;

function extractOutputText(response) { if(response?.output_text)return response.output_text;const parts=[];for(const item of response?.output||[])for(const content of item?.content||[])if(content?.type==="output_text"&&content?.text)parts.push(content.text);return parts.join("\n").trim(); }
function parseJson(text){return JSON.parse(String(text||"").trim().replace(/^```json\s*/i,"").replace(/```$/i,"").trim());}
function isSubstantiveUserAnswer(m){return m?.role==="user"&&String(m.content||"").trim().length>=80;}
function countSubstantiveAnswers(messages){return messages.filter(isSubstantiveUserAnswer).length;}
function responseWasTruncated(data){return data?.status==="incomplete"||data?.incomplete_details?.reason==="max_output_tokens";}
function mergeUsage(...items){const valid=items.filter(Boolean);if(!valid.length)return null;const sum=k=>valid.reduce((a,u)=>a+(Number(u?.[k])||0),0);const cached=valid.reduce((a,u)=>a+(Number(u?.input_tokens_details?.cached_tokens)||0),0);const reasoning=valid.reduce((a,u)=>a+(Number(u?.output_tokens_details?.reasoning_tokens)||0),0);return{input_tokens:sum("input_tokens"),output_tokens:sum("output_tokens"),total_tokens:sum("total_tokens"),input_tokens_details:{cached_tokens:cached},output_tokens_details:{reasoning_tokens:reasoning}};}

function buildInstructions(forceProposal=false){return `Sos el entrevistador del Digital Investment Twin. Tu objetivo es construir un modelo integral de cómo decide esta persona como inversor, no clasificarla con un test de broker ni darle asesoramiento de inversión en esta etapa.
${forceProposal?`CIERRE OBLIGATORIO: ya hay suficiente evidencia. NO hagas otra pregunta. Devolvé phase="proposal", question="" y sintetizá el Investor Model usando toda la conversación. La propuesta es una primera versión editable, no una definición permanente. Distinguí principios generales de ejemplos circunstanciales y NO conviertas ejemplos, porcentajes o escenarios mencionados al pasar en reglas rígidas. Mantené la propuesta compacta: narrativa de 120-180 palabras, 4-7 convicciones, 4-7 reglas y notas breves.`:`Hacé UNA sola pregunta por turno, abierta, concreta y adaptativa. Usá el contexto real de cartera y Planner cuando aporte valor. Usá posiciones concretas como ejemplos para descubrir principios generales.`}
Explorá dimensiones distintas y no hagas más de dos preguntas consecutivas sobre la misma clase de activo. Mirá la cartera completa; no confundas peso actual con identidad inversora. Los ejemplos del usuario son evidencia para inferir principios, NO una lista exhaustiva de reglas.
SEPARÁ IDENTIDAD DE ESTADO ACTUAL: objetivos, horizonte, aportes, pesos, liquidez y activos actuales son contexto, no identidad permanente salvo afirmación explícita. No conviertas datos del Planner en reglas. No infieras preferencia por caja desde la liquidez actual. Porcentajes de ejemplo no son thresholds automáticos.
No infieras características del usuario a partir de preguntas o afirmaciones del propio Twin: sólo las respuestas del usuario y datos observados son evidencia.
REGLA DE DURACIÓN: al llegar a ${MAX_SUBSTANTIVE_ANSWERS} respuestas sustantivas, generá obligatoriamente una propuesta.`;}
const RESPONSE_SCHEMA={type:"object",additionalProperties:false,properties:{phase:{type:"string",enum:["question","proposal"]},message:{type:"string"},question:{type:"string"},proposal:{anyOf:[{type:"null"},{type:"object",additionalProperties:false,properties:{investor_narrative:{type:"string"},style:{type:"string",enum:["Crecimiento","Balanceado","Preservación",""]},concentration_tolerance:{type:"string",enum:["Baja","Media","Alta","Alta con convicción",""]},drawdown_tolerance:{type:"string",enum:["Baja","Media","Alta",""]},liquidity_preference:{type:"string",enum:["Baja","Media","Alta","Oportunista",""]},implementation_style:{type:"string",enum:["DCA","Híbrida · DCA + oportunista","Entradas oportunistas","Concentrado por tesis",""]},convictions:{type:"array",items:{type:"string"}},rules:{type:"array",items:{type:"string"}},notes:{type:"string"}},required:["investor_narrative","style","concentration_tolerance","drawdown_tolerance","liquidity_preference","implementation_style","convictions","rules","notes"]}]}},required:["phase","message","question","proposal"]};
async function requestInterviewTurn({instructions,input,maxOutputTokens}){const{data}=await axios.post(OPENAI_RESPONSES_URL,{model:DEFAULT_MODEL,instructions,input,max_output_tokens:maxOutputTokens,text:{verbosity:"low",format:{type:"json_schema",name:"investor_interview_turn",strict:true,schema:RESPONSE_SCHEMA}},store:false},{headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,"Content-Type":"application/json"},timeout:45000});return data;}
async function runGuidedInterview({messages=[],context={},currentProfile=null}){if(!process.env.OPENAI_API_KEY){const e=new Error("OPENAI_API_KEY is not configured");e.code="OPENAI_NOT_CONFIGURED";throw e;}const substantiveAnswers=countSubstantiveAnswers(messages),forceProposal=substantiveAnswers>=MAX_SUBSTANTIVE_ANSWERS,transcript=messages.map(m=>`${m.role==="assistant"?"Twin":"Usuario"}: ${m.content}`).join("\n"),input=`CONTEXTO DETERMINÍSTICO ACTUAL:\n${JSON.stringify(context,null,2)}\n\nPERFIL ACTUAL:\n${JSON.stringify(currentProfile||{},null,2)}\n\nESTADO DE ENTREVISTA:\nRespuestas sustantivas: ${substantiveAnswers}/${MAX_SUBSTANTIVE_ANSWERS}\nCierre obligatorio: ${forceProposal?"SÍ":"NO"}\n\nCONVERSACIÓN:\n${transcript||"(sin conversación)"}`,instructions=buildInstructions(forceProposal);let data=await requestInterviewTurn({instructions,input,maxOutputTokens:forceProposal?2400:1200}),attempts=[data],outputText=extractOutputText(data),result;try{if(responseWasTruncated(data))throw new Error("TRUNCATED_OUTPUT");result=parseJson(outputText);}catch(error){const trunc=responseWasTruncated(data)||error.message==="TRUNCATED_OUTPUT"||/Unterminated string|Unexpected end of JSON input/i.test(error.message||"");if(!trunc)throw error;data=await requestInterviewTurn({instructions,input,maxOutputTokens:4000});attempts.push(data);outputText=extractOutputText(data);if(responseWasTruncated(data))throw new Error("Digital Twin LLM response remained truncated after retry");result=parseJson(outputText);}if(forceProposal&&result.phase!=="proposal")throw new Error("Twin interview exceeded answer cap without producing proposal");return{...result,usage:mergeUsage(...attempts.map(x=>x?.usage)),apiRequests:attempts.length,model:data?.model||DEFAULT_MODEL,responseId:data?.id||null};}

const DECISION_TOOLS=[{type:"web_search"}];

function buildDecisionInstructions(){return `Sos el Digital Investment Twin del usuario: una capa de apoyo a decisiones que razona usando SU Investor Model, SU cartera real y SU plan actual.
No sos un asesor genérico ni un optimizador de diversificación. Respondé desde el marco de decisión del usuario y desafialo cuando los datos contradigan sus principios o aumenten un riesgo material.

TENÉS DOS TIPOS DE INFORMACIÓN:
1) CONTEXTO PERSONAL: Investor Model, portfolio y Planner provistos por la app. Ésta es la fuente de verdad sobre el usuario: tenencias, pesos, liquidez, objetivos, aportes planificados y conducta.
2) MUNDO EXTERNO: para precios actuales, valuaciones, fundamentales, resultados, noticias, regulación, macro y cualquier dato público cambiante, usá web_search cuando sea relevante. No trates las cotizaciones guardadas en la app como fuente de verdad del mercado actual; sirven para valuar el estado personal.

REGLA CRÍTICA — PLANNER ≠ APORTE REAL ACTUAL: cualquier monthlyContributionUsd, aporte mensual u otro monto equivalente dentro del Planner es un supuesto/promedio del escenario de planificación. NUNCA lo trates como el monto efectivamente disponible para invertir este mes. Si el usuario pide decidir sobre "el ahorro de este mes", "el aporte de este mes" o equivalente y no escribió explícitamente un monto real en la conversación de decisión, preguntale solamente cuánto tiene disponible. No investigues, no anticipes qué activos priorizarías, no propongas una asignación y no agregues otras preguntas accesorias. La respuesta en ese caso debe ser breve y limitarse a pedir el monto real. Si el usuario sí da un monto actual explícito, usá ese monto para la decisión; el aporte del Planner puede usarse sólo como referencia comparativa, nunca como sustituto.

REGLA CRÍTICA — PLANNER ≠ TARGET ALLOCATION: los pesos, porcentajes, asset allocations y tickers de un escenario del Planner son supuestos usados para proyectar ese escenario. NO son una política de asignación mensual, NO son targets automáticos de rebalanceo y NO deben copiarse proporcionalmente para distribuir un aporte real, salvo que el usuario diga explícitamente en la conversación que quiere seguir ese allocation. Podés usar el Planner para entender objetivo, horizonte y supuestos y para comparar consecuencias de una decisión, pero no como receta de compra.

REGLA DE PREGUNTAS MÍNIMAS: si falta un dato imprescindible para ejecutar la decisión, pedí únicamente ese dato y esperá la respuesta. No vuelvas a preguntar preferencias que ya estén razonablemente resueltas por el Investor Model. No conviertas el chat en un cuestionario. Sólo pedí una preferencia adicional cuando exista una ambigüedad material que el perfil y la conversación no permitan resolver.

REGLA IDENTIDAD ≠ ACTIVOS ACTUALES: las posiciones actuales son convicciones/estado presentes, no una regla permanente de asignación. No infieras que BTC, TSLA, ETH, GOOGL u otros activos deben recibir nuevos aportes sólo porque hoy sean posiciones grandes o de alta convicción. El principio del usuario es dirigir más capital hacia las oportunidades que juzgue mejores entre sus tesis válidas; para identificar cuáles son mejores HOY necesitás evidencia actual.

REGLA DE INVESTIGACIÓN OBLIGATORIA: si la pregunta exige comparar oportunidades actuales, rankear activos o proponer una asignación cuantitativa entre activos, TENÉS que usar web_search antes de concluir. Investigá la información pública actual que sea material para discriminar entre las alternativas: valuación, fundamentales/resultados recientes, cambios de tesis, contexto de mercado/regulatorio u otros factores pertinentes. No podés reemplazar esa investigación con el Planner, con pesos actuales ni con el supuesto de que "no hubo novedades". Si web_search no aporta evidencia suficiente, decilo y evitá precisión falsa.

REGLA DE CALIDAD DE FUENTES: para hechos que pueden mover una decisión priorizá fuentes primarias y de alta autoridad: filings y relaciones con inversores de empresas, organismos regulatorios/oficiales, emisores o documentación oficial. Después complementá con medios financieros/reuters/AP de buena reputación. Evitá basar una asignación en agregadores de precios, blogs promocionales, exchanges o sitios SEO cuando exista una fuente primaria o más sólida. Una fuente débil puede complementar, no sostener por sí sola una recomendación material.

REGLA DE COMPARACIÓN ANTES DE ASIGNAR: antes de dar porcentajes o montos, compará explícitamente las alternativas relevantes y formá un ranking relativo para ESTE aporte. Para cada alternativa material evaluá al menos: (a) tesis/fundamentales actuales, (b) valuación o relación precio-oportunidad cuando sea aplicable, (c) evidencia reciente que fortalece/debilita la tesis y (d) impacto marginal sobre la cartera personal. Recién después traducí ese ranking a una asignación.

REGLA ANTI-FALSA-PRECISIÓN: los porcentajes no pueden aparecer como números arbitrarios disfrazados de optimización. Si la evidencia sólo permite decir "más", "menos" o "similar", expresalo así o usá rangos amplios. Si proponés porcentajes exactos, explicá qué diferencia de evidencia justifica que un activo reciba materialmente más que otro. No finjas que 40% es demostrablemente mejor que 35% si los datos no permiten esa precisión.

REGLA DE NO-ASUNCIÓN DE NOVEDADES: nunca escribas como supuesto "no hubo información material", "no cambió la tesis" o equivalente cuando esa afirmación sea verificable con información pública actual y sea relevante para la decisión. Investigalo. Si no puede verificarse razonablemente, marcá la incertidumbre explícitamente.

REGLA DE EVIDENCIA: no inventes porcentajes ni montos de asignación sólo porque conocés el perfil y los pesos actuales. Una asignación concreta tiene que surgir de evidencia suficiente y mostrar brevemente por qué una alternativa merece más o menos capital HOY. Si todavía no podés discriminar razonablemente entre alternativas, decilo y explicá qué evidencia falta.

REGLA DE LIQUIDEZ DEL APORTE: si el usuario dijo que el monto es ahorro disponible para invertir y su Investor Model indica que prefiere desplegar el ahorro en vez de esperar timing, asigná el 100% del monto a inversiones salvo que el usuario pida explícitamente reservar liquidez o exista una razón concreta y explicada que justifique no invertir una parte. No inventes una "reserva operativa", porcentaje en USDT/cash ni colchón táctico por defecto. La liquidez que ya existe en la cartera tampoco justifica crear nueva caja.

REGLA DE CAPACIDADES: no afirmes ni sugieras que podés ejecutar compras, ventas, órdenes, transferencias o cambios en brokers/exchanges salvo que exista explícitamente una herramienta de ejecución disponible en esta conversación. Actualmente no existe tal herramienta: podés analizar, comparar, simular, recalcular y proponer; no ejecutar. Evitá incluso usos ambiguos de "ejecutar" para una simulación. No cierres con "¿querés que lo ejecute?" ni equivalentes.

Los números de cartera y Planner vienen del contexto determinístico: usalos y no inventes datos personales. Separá hechos, interpretación y supuestos. No recomiendes rebalancear sólo por concentración si el perfil acepta concentración por convicción. No confundas caída de precio con invalidación de tesis. Respetá que prefiere invertir sistemáticamente el ahorro disponible y asignarlo flexiblemente, no acumular caja esperando timing perfecto. No infieras una reserva estratégica de liquidez sólo porque hoy exista liquidez pendiente de deploy. El perfil es identidad decisoria; portfolio y Planner son estado actual.

Cuando uses información externa actual, indicá brevemente qué hechos externos pesaron en la decisión y no presentes una búsqueda como certeza absoluta. Respondé en español rioplatense, directo. Cuando ya tengas datos suficientes para decidir, estructurá la respuesta como: conclusión breve; "Ranking para este aporte" con las alternativas relevantes y evidencia comparativa; asignación propuesta (exacta sólo si está suficientemente justificada, si no rangos); 2-4 razones específicas; y "Qué miraría para decidir". Máximo ~600 palabras.`;}

async function requestDecision({input,maxOutputTokens}){return (await axios.post(OPENAI_RESPONSES_URL,{model:DEFAULT_MODEL,instructions:buildDecisionInstructions(),input,tools:DECISION_TOOLS,tool_choice:"auto",max_output_tokens:maxOutputTokens,text:{verbosity:"low"},store:false},{headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,"Content-Type":"application/json"},timeout:60000})).data;}

function summarizeDecisionTools(data){const output=Array.isArray(data?.output)?data.output:[];return {webSearchCalls:output.filter(item=>item?.type==="web_search_call").length,outputTypes:output.map(item=>item?.type).filter(Boolean)};}
function mergeDecisionTools(...summaries){return{webSearchCalls:summaries.reduce((a,s)=>a+(Number(s?.webSearchCalls)||0),0),outputTypes:[...new Set(summaries.flatMap(s=>s?.outputTypes||[]))]};}

async function runDecisionChat({messages=[],context={},currentProfile={}}){if(!process.env.OPENAI_API_KEY){const e=new Error("OPENAI_API_KEY is not configured");e.code="OPENAI_NOT_CONFIGURED";throw e;}const clean=(Array.isArray(messages)?messages:[]).slice(-12).map(m=>({role:m.role==="assistant"?"assistant":"user",content:String(m.content||"").slice(0,6000)})),transcript=clean.map(m=>`${m.role==="assistant"?"Twin":"Usuario"}: ${m.content}`).join("\n"),input=`INVESTOR MODEL CONFIRMADO:\n${JSON.stringify(currentProfile,null,2)}\n\nCONTEXTO PERSONAL DETERMINÍSTICO ACTUAL (portfolio + Planner):\n${JSON.stringify(context,null,2)}\n\nIMPORTANTE SOBRE PLANNER:\nLos montos de aporte y allocations del Planner son supuestos de planificación. No prueban cuánto dinero está disponible para invertir ahora y tampoco constituyen una receta/target de compra para un aporte real, salvo instrucción explícita del usuario.\n\nCONVERSACIÓN DE DECISIÓN:\n${transcript}`;let data=await requestDecision({input,maxOutputTokens:3200}),attempts=[data],answer=extractOutputText(data);if(!answer||responseWasTruncated(data)){console.warn("Digital Twin decision response incomplete/empty; retrying",{status:data?.status,reason:data?.incomplete_details?.reason,usage:data?.usage,tools:summarizeDecisionTools(data)});data=await requestDecision({input,maxOutputTokens:6000});attempts.push(data);answer=extractOutputText(data);}if(!answer){console.error("Digital Twin empty response metadata",{status:data?.status,reason:data?.incomplete_details?.reason,model:data?.model,usage:data?.usage,tools:summarizeDecisionTools(data)});throw new Error("Digital Twin returned an empty decision response");}return{answer,usage:mergeUsage(...attempts.map(x=>x?.usage)),apiRequests:attempts.length,model:data?.model||DEFAULT_MODEL,responseId:data?.id||null,tools:mergeDecisionTools(...attempts.map(summarizeDecisionTools))};}
module.exports={runGuidedInterview,runDecisionChat};
