const axios = require("axios");

const OPENAI_RESPONSES_URL = "https://api.openai.com/v1/responses";
const DEFAULT_MODEL = process.env.DIGITAL_TWIN_MODEL || "gpt-5-mini";
const MAX_SUBSTANTIVE_ANSWERS = 6;

function extractOutputText(response) { if(response?.output_text)return response.output_text;const parts=[];for(const item of response?.output||[])for(const content of item?.content||[])if(content?.type==="output_text"&&content?.text)parts.push(content.text);return parts.join("\n").trim(); }
function parseJson(text){return JSON.parse(String(text||"").trim().replace(/^```json\s*/i,"").replace(/```$/i,"").trim());}
function isSubstantiveUserAnswer(m){return m?.role==="user"&&String(m.content||"").trim().length>=80;}
function countSubstantiveAnswers(messages){return messages.filter(isSubstantiveUserAnswer).length;}
function responseWasTruncated(data){return data?.status==="incomplete"||data?.incomplete_details?.reason==="max_output_tokens";}
function mergeUsage(...items){const valid=items.filter(Boolean);if(!valid.length)return null;const sum=k=>valid.reduce((a,u)=>a+(Number(u?.[k])||0),0);const cached=valid.reduce((a,u)=>a+(Number(u?.input_tokens_details?.cached_tokens)||0),0);const reasoning=valid.reduce((a,u)=>a+(Number(u?.output_tokens_details?.reasoning_tokens)||0),0);return{input_tokens:sum("input_tokens"),output_tokens:sum("output_tokens"),total_tokens:sum("total_tokens"),input_tokens_details:{cached_tokens:cached},output_tokens_details:{reasoning_tokens:reasoning}};}

function buildInstructions(forceProposal=false){return `Sos el entrevistador del Digital Investment Twin. Tu objetivo es construir un modelo integral de cómo decide esta persona como inversor, no clasificarla con un test de broker ni darle asesoramiento de inversión en esta etapa.
${forceProposal?`CIERRE OBLIGATORIO: ya hay suficiente evidencia. NO hagas otra pregunta. Devolvé phase="proposal", question="" y sintetizá el Investor Model usando toda la conversación. La propuesta es una primera versión editable, no una definición permanente. Distinguí principios generales de ejemplos circunstanciales y NO conviertas ejemplos, porcentajes o escenarios mencionados al pasar en reglas rígidas. Mantené la propuesta compacta: narrativa de 120-180 palabras, 4-7 convicciones, 4-7 reglas y notas breves.`:`Hacé UNA sola pregunta por turno, abierta, concreta y adaptativa. Usá el contexto real de cartera y Planner cuando aporte valor. Usá posiciones concretas como ejemplos para descubrir principios generales.`}
Explorá dimensiones distintas y no hagas más de dos preguntas consecutivas sobre la misma clase de activo. Mirá la cartera completa; no confundas peso actual con identidad inversora. Los ejemplos del usuario son evidencia para inferir principios, NO una lista exhaustiva de reglas.
SEPARÁ IDENTIDAD DE ESTADO ACTUAL: objetivos, horizonte, aportes, pesos, liquidez y activos actuales son contexto, no identidad permanente salvo afirmación explícita. No conviertas datos del Planner en reglas. No infieras preferencia por caja desde la liquidez actual. Porcentajes de ejemplo no son thresholds automáticos.
No infieras características del usuario a partir de preguntas o afirmaciones del propio Twin: sólo las respuestas del usuario y datos observados son evidencia.
REGLA DE DURACIÓN: al llegar a ${MAX_SUBSTANTIVE_ANSWERS} respuestas sustantivas, generá obligatoriamente una propuesta.`;}
const RESPONSE_SCHEMA={type:"object",additionalProperties:false,properties:{phase:{type:"string",enum:["question","proposal"]},message:{type:"string"},question:{type:"string"},proposal:{anyOf:[{type:"null"},{type:"object",additionalProperties:false,properties:{investor_narrative:{type:"string"},style:{type:"string",enum:["Crecimiento","Balanceado","Preservación",""]},concentration_tolerance:{type:"string",enum:["Baja","Media","Alta","Alta con convicción",""]},drawdown_tolerance:{type:"string",enum:["Baja","Media","Alta",""]},liquidity_preference:{type:"string",enum:["Baja","Media","Alta","Oportunista",""]},implementation_style:{type:"string",enum:["DCA","Híbrida · DCA + oportunista","Entradas oportunistas","Concentrado por tesis",""]},convictions:{type:"array",items:{type:"string"}},rules:{type:"array",items:{type:"string"}},notes:{type:"string"}},required:["investor_narrative","style","concentration_tolerance","drawdown_tolerance","liquidity_preference","implementation_style","convictions","rules","notes"]}]}},required:["phase","message","question","proposal"]};
async function requestInterviewTurn({instructions,input,maxOutputTokens}){const{data}=await axios.post(OPENAI_RESPONSES_URL,{model:DEFAULT_MODEL,instructions,input,max_output_tokens:maxOutputTokens,text:{verbosity:"low",format:{type:"json_schema",name:"investor_interview_turn",strict:true,schema:RESPONSE_SCHEMA}},store:false},{headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,"Content-Type":"application/json"},timeout:45000});return data;}
async function runGuidedInterview({messages=[],context={},currentProfile=null}){if(!process.env.OPENAI_API_KEY){const e=new Error("OPENAI_API_KEY is not configured");e.code="OPENAI_NOT_CONFIGURED";throw e;}const substantiveAnswers=countSubstantiveAnswers(messages),forceProposal=substantiveAnswers>=MAX_SUBSTANTIVE_ANSWERS,transcript=messages.map(m=>`${m.role==="assistant"?"Twin":"Usuario"}: ${m.content}`).join("\n"),input=`CONTEXTO DETERMINÍSTICO ACTUAL:\n${JSON.stringify(context,null,2)}\n\nPERFIL ACTUAL:\n${JSON.stringify(currentProfile||{},null,2)}\n\nESTADO DE ENTREVISTA:\nRespuestas sustantivas: ${substantiveAnswers}/${MAX_SUBSTANTIVE_ANSWERS}\nCierre obligatorio: ${forceProposal?"SÍ":"NO"}\n\nCONVERSACIÓN:\n${transcript||"(sin conversación)"}`,instructions=buildInstructions(forceProposal);let data=await requestInterviewTurn({instructions,input,maxOutputTokens:forceProposal?2400:1200}),attempts=[data],outputText=extractOutputText(data),result;try{if(responseWasTruncated(data))throw new Error("TRUNCATED_OUTPUT");result=parseJson(outputText);}catch(error){const trunc=responseWasTruncated(data)||error.message==="TRUNCATED_OUTPUT"||/Unterminated string|Unexpected end of JSON input/i.test(error.message||"");if(!trunc)throw error;data=await requestInterviewTurn({instructions,input,maxOutputTokens:4000});attempts.push(data);outputText=extractOutputText(data);if(responseWasTruncated(data))throw new Error("Digital Twin LLM response remained truncated after retry");result=parseJson(outputText);}if(forceProposal&&result.phase!=="proposal")throw new Error("Twin interview exceeded answer cap without producing proposal");return{...result,usage:mergeUsage(...attempts.map(x=>x?.usage)),apiRequests:attempts.length,model:data?.model||DEFAULT_MODEL,responseId:data?.id||null};}

const DECISION_TOOLS=[{type:"web_search"}];
const PREFLIGHT_SCHEMA={type:"object",additionalProperties:false,properties:{decisionType:{type:"string",enum:["allocation","asset_question","portfolio_risk","sell_hold","plan_progress","other"]},missingCriticalInputs:{type:"array",items:{type:"string"}},questionForUser:{type:"string"},candidateUniverse:{type:"array",items:{type:"string"}},screening:{type:"array",items:{type:"object",additionalProperties:false,properties:{asset:{type:"string"},status:{type:"string",enum:["candidate","deprioritized","insufficient_evidence"]},reason:{type:"string"},personalImpact:{type:"string"}},required:["asset","status","reason","personalImpact"]}},shortlist:{type:"array",items:{type:"string"}},needsCurrentResearch:{type:"boolean"},researchQuestions:{type:"array",items:{type:"object",additionalProperties:false,properties:{asset:{type:"string"},question:{type:"string"},preferredSourceType:{type:"string"}},required:["asset","question","preferredSourceType"]}},requiresQuantitativeAllocation:{type:"boolean"},allocationAmountUsd:{anyOf:[{type:"number"},{type:"null"}]},planningNotes:{type:"array",items:{type:"string"}}},required:["decisionType","missingCriticalInputs","questionForUser","candidateUniverse","screening","shortlist","needsCurrentResearch","researchQuestions","requiresQuantitativeAllocation","allocationAmountUsd","planningNotes"]};

function buildPreflightInstructions(){return `Sos el Decision Planner interno del Digital Investment Twin. NO respondas al usuario y NO investigues la web. Tu salida es un plan estructurado y auditable para que otro modelo tome la decisión.
Usá exclusivamente el Investor Model confirmado, la cartera/Planner determinísticos y la conversación. No inventes hechos externos actuales.
IDENTIDAD ≠ ESTADO: no infieras preferencia por cripto, acciones ni un ticker porque tenga peso alto. Concentración y tolerancia a volatilidad tampoco implican preferencia por una clase de activo.
PLANNER: aporte mensual y allocations son supuestos de planificación, no dinero disponible ni targets de compra.
DATOS FALTANTES: si falta un dato realmente imprescindible, incluilo en missingCriticalInputs y formulá UNA pregunta mínima en questionForUser. Para "ahorro/aporte de este mes" sin monto explícito, pedí sólo el monto. Si no falta nada, questionForUser debe ser "".
ALLOCATION ABIERTA: candidateUniverse debe partir de todas las inversiones actuales económicamente relevantes presentes en el contexto, no sólo las posiciones grandes. Cada activo del universo debe aparecer una vez en screening. El screening es preliminar: sin evidencia externa actual no afirmes que una tesis está intacta, que un activo está barato/caro ni que noticias recientes lo favorecen. Si eso es necesario para discriminar, usá status candidate o insufficient_evidence y pedí investigación.
No descartes un activo sólo por ser una posición pequeña, ni priorices uno sólo por ser grande. Shortlist debe surgir de razones personales/determinísticas y de qué comparaciones externas vale la pena investigar; no de una recomendación anticipada.
RESEARCH: researchQuestions debe especificar qué evidencia externa discriminante necesita la decisión y qué fuente preferir: primary/company_ir/regulator/official_data/reuters_ap. Priorizá fuentes primarias.
No inventes porcentajes de asignación. Esta fase decide QUÉ hay que comparar, no cuánto comprar.`;}

async function requestPreflight({input,maxOutputTokens=1800}){return (await axios.post(OPENAI_RESPONSES_URL,{model:DEFAULT_MODEL,instructions:buildPreflightInstructions(),input,max_output_tokens:maxOutputTokens,text:{verbosity:"low",format:{type:"json_schema",name:"digital_twin_decision_preflight",strict:true,schema:PREFLIGHT_SCHEMA}},store:false},{headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,"Content-Type":"application/json"},timeout:45000})).data;}

async function runDecisionPreflight({messages,context,currentProfile}){const clean=(Array.isArray(messages)?messages:[]).slice(-10).map(m=>({role:m.role==="assistant"?"assistant":"user",content:String(m.content||"").slice(0,4000)}));const input=`INVESTOR MODEL CONFIRMADO:\n${JSON.stringify(currentProfile||{},null,2)}\n\nCONTEXTO PERSONAL DETERMINÍSTICO (portfolio + Planner):\n${JSON.stringify(context||{},null,2)}\n\nCONVERSACIÓN:\n${clean.map(m=>`${m.role==="assistant"?"Twin":"Usuario"}: ${m.content}`).join("\n")}`;let data=await requestPreflight({input}),attempts=[data],text=extractOutputText(data),plan;try{if(responseWasTruncated(data))throw new Error("TRUNCATED_OUTPUT");plan=parseJson(text);}catch(error){const trunc=responseWasTruncated(data)||/TRUNCATED_OUTPUT|Unterminated string|Unexpected end of JSON input/i.test(error.message||"");if(!trunc)throw error;data=await requestPreflight({input,maxOutputTokens:3000});attempts.push(data);plan=parseJson(extractOutputText(data));}return{plan,attempts};}

function buildDecisionInstructions(){return `Sos el Digital Investment Twin. Recibís un PRE-FLIGHT estructurado ya generado con Investor Model + cartera + Planner. Tu trabajo es investigar lo que el preflight pide y responder la decisión, no rehacer silenciosamente el universo.
La app es fuente de verdad de datos personales. Para mundo externo cambiante usá web_search. Para decisiones actuales que el preflight marque como research, investigá antes de concluir.
FUENTES: priorizá company IR/filings, SEC/reguladores, organismos y fuentes oficiales/directas; después Reuters/AP/medios financieros sólidos. No sostengas decisiones materiales sólo con agregadores, exchanges, blogs SEO o medios cripto si hay una fuente mejor.
FIDELIDAD AL PREFLIGHT: respetá candidateUniverse, screening y shortlist. Podés cambiar el status/ranking de un activo sólo si la investigación externa aporta evidencia que lo justifique, y explicá ese cambio. Un activo deprioritized no puede reaparecer en la asignación como "opcional" sin evidencia nueva explícita.
IDENTIDAD ≠ ESTADO: no digas "preferencia por cripto", "BTC es tu mayor convicción", "núcleo del plan" o equivalentes salvo que eso figure explícitamente en Investor Model. Peso actual no es identidad.
PLANNER ≠ TARGET: no copies allocations del Planner ni ofrezcas seguirlas salvo pedido explícito.
ASIGNACIÓN: primero evidencia y ranking, después implementación. No inventes precisión matemática. Si la evidencia sólo sostiene más/menos/similar, usá rangos o explicá que los montos exactos son redondeo práctico. Si proponés un reparto exacto, explicá por qué la diferencia material entre activos merece ese reparto. Si el Investor Model indica desplegar el ahorro disponible, invertí 100% salvo razón concreta o pedido contrario; no inventes caja.
CAPACIDADES: podés analizar, comparar, simular y proponer. No podés ejecutar órdenes. No uses "ejecutar" ambiguamente ni cierres ofreciendo market/limit, timing, tramos o pasos de broker salvo pedido.
Respondé en español rioplatense, directo, máximo ~650 palabras. Para allocation abierta: Conclusión; Screening (incluyendo descartes materiales); Ranking para este aporte; Asignación (evidencia vs criterio práctico); 2-4 razones; Qué podría cambiar la decisión. No agregues una pregunta final accesoria.`;}

async function requestDecision({input,maxOutputTokens}){return (await axios.post(OPENAI_RESPONSES_URL,{model:DEFAULT_MODEL,instructions:buildDecisionInstructions(),input,tools:DECISION_TOOLS,tool_choice:"auto",max_output_tokens:maxOutputTokens,text:{verbosity:"low"},store:false},{headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,"Content-Type":"application/json"},timeout:60000})).data;}
function summarizeDecisionTools(data){const output=Array.isArray(data?.output)?data.output:[];return {webSearchCalls:output.filter(item=>item?.type==="web_search_call").length,outputTypes:output.map(item=>item?.type).filter(Boolean)};}
function mergeDecisionTools(...summaries){return{webSearchCalls:summaries.reduce((a,s)=>a+(Number(s?.webSearchCalls)||0),0),outputTypes:[...new Set(summaries.flatMap(s=>s?.outputTypes||[]))]};}

async function runDecisionChat({messages=[],context={},currentProfile={}}){if(!process.env.OPENAI_API_KEY){const e=new Error("OPENAI_API_KEY is not configured");e.code="OPENAI_NOT_CONFIGURED";throw e;}
const {plan,attempts:preflightAttempts}=await runDecisionPreflight({messages,context,currentProfile});
if(plan.missingCriticalInputs?.length){return{answer:plan.questionForUser||`Me falta un dato para decidir: ${plan.missingCriticalInputs[0]}`,preflight:plan,usage:mergeUsage(...preflightAttempts.map(x=>x?.usage)),apiRequests:preflightAttempts.length,model:preflightAttempts.at(-1)?.model||DEFAULT_MODEL,responseId:preflightAttempts.at(-1)?.id||null,tools:{webSearchCalls:0,outputTypes:[]}};}
const clean=(Array.isArray(messages)?messages:[]).slice(-10).map(m=>({role:m.role==="assistant"?"assistant":"user",content:String(m.content||"").slice(0,4000)}));
const input=`INVESTOR MODEL CONFIRMADO:\n${JSON.stringify(currentProfile,null,2)}\n\nCONTEXTO PERSONAL DETERMINÍSTICO:\n${JSON.stringify(context,null,2)}\n\nPRE-FLIGHT DE DECISIÓN (auditable; usalo como plan):\n${JSON.stringify(plan,null,2)}\n\nCONVERSACIÓN:\n${clean.map(m=>`${m.role==="assistant"?"Twin":"Usuario"}: ${m.content}`).join("\n")}`;
let data=await requestDecision({input,maxOutputTokens:4200}),decisionAttempts=[data],answer=extractOutputText(data);if(!answer||responseWasTruncated(data)){console.warn("Digital Twin final decision incomplete/empty; retrying",{status:data?.status,reason:data?.incomplete_details?.reason,usage:data?.usage,tools:summarizeDecisionTools(data)});data=await requestDecision({input,maxOutputTokens:7000});decisionAttempts.push(data);answer=extractOutputText(data);}if(!answer)throw new Error("Digital Twin returned an empty decision response");
const allAttempts=[...preflightAttempts,...decisionAttempts];return{answer,preflight:plan,usage:mergeUsage(...allAttempts.map(x=>x?.usage)),apiRequests:allAttempts.length,model:data?.model||DEFAULT_MODEL,responseId:data?.id||null,tools:mergeDecisionTools(...decisionAttempts.map(summarizeDecisionTools))};}
module.exports={runGuidedInterview,runDecisionChat};