const axios = require("axios");

const OPENAI_RESPONSES_URL = "https://api.openai.com/v1/responses";
const DEFAULT_MODEL = process.env.DIGITAL_TWIN_MODEL || "gpt-5-mini";
const MAX_SUBSTANTIVE_ANSWERS = 6;

function extractOutputText(response) { if(response?.output_text)return response.output_text;const parts=[];for(const item of response?.output||[])for(const content of item?.content||[])if(content?.type==="output_text"&&content?.text)parts.push(content.text);return parts.join("\n").trim(); }
function parseJson(text){return JSON.parse(String(text||"").trim().replace(/^```json\s*/i,"").replace(/```$/i,"").trim());}
function isSubstantiveUserAnswer(m){return m?.role==="user"&&String(m.content||"").trim().length>=80;}
function countSubstantiveAnswers(messages){return messages.filter(isSubstantiveUserAnswer).length;}
function responseWasTruncated(data){return data?.status==="incomplete"||data?.incomplete_details?.reason==="max_output_tokens";}

function buildInstructions(forceProposal=false){return `Sos el entrevistador del Digital Investment Twin. Tu objetivo es construir un modelo integral de cómo decide esta persona como inversor, no clasificarla con un test de broker ni darle asesoramiento de inversión en esta etapa.
${forceProposal?`CIERRE OBLIGATORIO: ya hay suficiente evidencia. NO hagas otra pregunta. Devolvé phase="proposal", question="" y sintetizá el Investor Model usando toda la conversación. La propuesta es una primera versión editable, no una definición permanente. Distinguí principios generales de ejemplos circunstanciales y NO conviertas ejemplos, porcentajes o escenarios mencionados al pasar en reglas rígidas. Mantené la propuesta compacta: narrativa de 120-180 palabras, 4-7 convicciones, 4-7 reglas y notas breves.`:`Hacé UNA sola pregunta por turno, abierta, concreta y adaptativa. Usá el contexto real de cartera y Planner cuando aporte valor. Usá posiciones concretas como ejemplos para descubrir principios generales.`}
Explorá dimensiones distintas y no hagas más de dos preguntas consecutivas sobre la misma clase de activo. Mirá la cartera completa; no confundas peso actual con identidad inversora. Los ejemplos del usuario son evidencia para inferir principios, NO una lista exhaustiva de reglas.
SEPARÁ IDENTIDAD DE ESTADO ACTUAL: objetivos, horizonte, aportes, pesos, liquidez y activos actuales son contexto, no identidad permanente salvo afirmación explícita. No conviertas datos del Planner en reglas. No infieras preferencia por caja desde la liquidez actual. Porcentajes de ejemplo no son thresholds automáticos.
No infieras características del usuario a partir de preguntas o afirmaciones del propio Twin: sólo las respuestas del usuario y datos observados son evidencia.
REGLA DE DURACIÓN: al llegar a ${MAX_SUBSTANTIVE_ANSWERS} respuestas sustantivas, generá obligatoriamente una propuesta.`;}
const RESPONSE_SCHEMA={type:"object",additionalProperties:false,properties:{phase:{type:"string",enum:["question","proposal"]},message:{type:"string"},question:{type:"string"},proposal:{anyOf:[{type:"null"},{type:"object",additionalProperties:false,properties:{investor_narrative:{type:"string"},style:{type:"string",enum:["Crecimiento","Balanceado","Preservación",""]},concentration_tolerance:{type:"string",enum:["Baja","Media","Alta","Alta con convicción",""]},drawdown_tolerance:{type:"string",enum:["Baja","Media","Alta",""]},liquidity_preference:{type:"string",enum:["Baja","Media","Alta","Oportunista",""]},implementation_style:{type:"string",enum:["DCA","Híbrida · DCA + oportunista","Entradas oportunistas","Concentrado por tesis",""]},convictions:{type:"array",items:{type:"string"}},rules:{type:"array",items:{type:"string"}},notes:{type:"string"}},required:["investor_narrative","style","concentration_tolerance","drawdown_tolerance","liquidity_preference","implementation_style","convictions","rules","notes"]}]}},required:["phase","message","question","proposal"]};
async function requestInterviewTurn({instructions,input,maxOutputTokens}){const{data}=await axios.post(OPENAI_RESPONSES_URL,{model:DEFAULT_MODEL,instructions,input,max_output_tokens:maxOutputTokens,text:{verbosity:"low",format:{type:"json_schema",name:"investor_interview_turn",strict:true,schema:RESPONSE_SCHEMA}},store:false},{headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,"Content-Type":"application/json"},timeout:45000});return data;}
async function runGuidedInterview({messages=[],context={},currentProfile=null}){if(!process.env.OPENAI_API_KEY){const e=new Error("OPENAI_API_KEY is not configured");e.code="OPENAI_NOT_CONFIGURED";throw e;}const substantiveAnswers=countSubstantiveAnswers(messages),forceProposal=substantiveAnswers>=MAX_SUBSTANTIVE_ANSWERS,transcript=messages.map(m=>`${m.role==="assistant"?"Twin":"Usuario"}: ${m.content}`).join("\n"),input=`CONTEXTO DETERMINÍSTICO ACTUAL:\n${JSON.stringify(context,null,2)}\n\nPERFIL ACTUAL:\n${JSON.stringify(currentProfile||{},null,2)}\n\nESTADO DE ENTREVISTA:\nRespuestas sustantivas: ${substantiveAnswers}/${MAX_SUBSTANTIVE_ANSWERS}\nCierre obligatorio: ${forceProposal?"SÍ":"NO"}\n\nCONVERSACIÓN:\n${transcript||"(sin conversación)"}`,instructions=buildInstructions(forceProposal);let data=await requestInterviewTurn({instructions,input,maxOutputTokens:forceProposal?2400:1200}),outputText=extractOutputText(data),result;try{if(responseWasTruncated(data))throw new Error("TRUNCATED_OUTPUT");result=parseJson(outputText);}catch(error){const trunc=responseWasTruncated(data)||error.message==="TRUNCATED_OUTPUT"||/Unterminated string|Unexpected end of JSON input/i.test(error.message||"");if(!trunc)throw error;data=await requestInterviewTurn({instructions,input,maxOutputTokens:4000});outputText=extractOutputText(data);if(responseWasTruncated(data))throw new Error("Digital Twin LLM response remained truncated after retry");result=parseJson(outputText);}if(forceProposal&&result.phase!=="proposal")throw new Error("Twin interview exceeded answer cap without producing proposal");return{...result,usage:data?.usage||null,model:data?.model||DEFAULT_MODEL,responseId:data?.id||null};}

function buildDecisionInstructions(){return `Sos el Digital Investment Twin del usuario: una capa de apoyo a decisiones que razona usando SU Investor Model, SU cartera real y SU plan actual.
No sos un asesor genérico ni un optimizador de diversificación. Respondé desde el marco de decisión del usuario y desafialo cuando los datos contradigan sus principios o aumenten un riesgo material.
Los números de cartera y Planner vienen del contexto determinístico: usalos y no inventes datos. Separá hechos, interpretación y supuestos. Si faltan valuación, fundamentales o mercado actual para elegir entre activos, decilo explícitamente. No recomiendes rebalancear sólo por concentración si el perfil acepta concentración por convicción. No confundas caída de precio con invalidación de tesis. Respetá que prefiere invertir sistemáticamente el ahorro disponible y asignarlo flexiblemente, no acumular caja esperando timing perfecto. El perfil es identidad decisoria; portfolio y Planner son estado actual.
Respondé en español rioplatense, directo. Empezá con una conclusión breve, seguí con 2-4 razones específicas y cerrá con "Qué miraría para decidir". Máximo ~400 palabras.`;}
async function requestDecision({input,maxOutputTokens}){return (await axios.post(OPENAI_RESPONSES_URL,{model:DEFAULT_MODEL,instructions:buildDecisionInstructions(),input,max_output_tokens:maxOutputTokens,text:{verbosity:"low"},store:false},{headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,"Content-Type":"application/json"},timeout:45000})).data;}
async function runDecisionChat({messages=[],context={},currentProfile={}}){if(!process.env.OPENAI_API_KEY){const e=new Error("OPENAI_API_KEY is not configured");e.code="OPENAI_NOT_CONFIGURED";throw e;}const clean=(Array.isArray(messages)?messages:[]).slice(-12).map(m=>({role:m.role==="assistant"?"assistant":"user",content:String(m.content||"").slice(0,6000)})),transcript=clean.map(m=>`${m.role==="assistant"?"Twin":"Usuario"}: ${m.content}`).join("\n"),input=`INVESTOR MODEL CONFIRMADO:\n${JSON.stringify(currentProfile,null,2)}\n\nCONTEXTO DETERMINÍSTICO ACTUAL (portfolio + Planner):\n${JSON.stringify(context,null,2)}\n\nCONVERSACIÓN DE DECISIÓN:\n${transcript}`;let data=await requestDecision({input,maxOutputTokens:2600}),answer=extractOutputText(data);if(!answer||responseWasTruncated(data)){console.warn("Digital Twin decision response incomplete/empty; retrying",{status:data?.status,reason:data?.incomplete_details?.reason,usage:data?.usage});data=await requestDecision({input,maxOutputTokens:5000});answer=extractOutputText(data);}if(!answer){console.error("Digital Twin empty response metadata",{status:data?.status,reason:data?.incomplete_details?.reason,model:data?.model,usage:data?.usage,outputTypes:(data?.output||[]).map(x=>x?.type)});throw new Error("Digital Twin returned an empty decision response");}return{answer,usage:data?.usage||null,model:data?.model||DEFAULT_MODEL,responseId:data?.id||null};}
module.exports={runGuidedInterview,runDecisionChat};
