const crypto = require("crypto");
const { getInvestorProfile } = require("./digitalTwinController");
const { runDecisionPipeline } = require("../services/digitalTwinDecisionPipeline");
const { runQuery } = require("../services/bigQueryService");
const { table } = require("../utils/bigqueryHelper");
const { interpretAndApplyPolicy, loadCurrentInvestmentPolicy } = require("../services/digitalTwinInvestmentPolicy");
const { persistDecision } = require("../services/digitalTwinMemoryService");
const { COST_SOURCE, usageBreakdown } = require("../services/aiPricingService");

function captureResponse(){let statusCode=200,payload;return{res:{status(code){statusCode=code;return this},json(value){payload=value;return value}},result(){return{statusCode,payload}}}}
function normalizeMessages(messages){return Array.isArray(messages)?messages.slice(-30).map(item=>({role:item?.role==="assistant"?"assistant":"user",content:String(item?.content||"").slice(0,4000)})).filter(item=>item.content.trim()):[]}
function mergeUsageStages(policyStage,resultStages=[]){return[policyStage,...resultStages].filter(Boolean)}
function mergeUsage(stages=[]){const us=stages.map(x=>x?.usage).filter(Boolean),sum=k=>us.reduce((a,x)=>a+(Number(x?.[k])||0),0);return{input_tokens:sum("input_tokens"),output_tokens:sum("output_tokens"),total_tokens:sum("total_tokens"),input_tokens_details:{cached_tokens:us.reduce((a,x)=>a+(Number(x?.input_tokens_details?.cached_tokens)||0),0)},output_tokens_details:{reasoning_tokens:us.reduce((a,x)=>a+(Number(x?.output_tokens_details?.reasoning_tokens)||0),0)}}}
function formatPolicyUpdate(u={}){if(u.status==="paused")return`${u.asset}: DCA pausado`;if(u.status==="stopped")return`${u.asset}: DCA detenido`;const n=Number(u.amount_usd),amount=Number.isFinite(n)?`US$${n.toLocaleString("en-US",{maximumFractionDigits:2})}`:"monto actualizado",freq=u.frequency==="daily"?"diarios":u.frequency==="weekly"?"semanales":u.frequency==="monthly"?"mensuales":"";return`${u.asset} a ${amount}${freq?` ${freq}`:""}`}
function policyUpdateAnswer(updates=[]){return`Registrado: ${updates.map(formatPolicyUpdate).join(" · ")}.`}
async function trackUsage(result,messageCount,stagesOverride=null){try{const stages=stagesOverride||result?.usageStages||[],usage=stagesOverride?mergeUsage(stages):(result?.usage||{}),b=usageBreakdown(stages);await runQuery(`INSERT INTO ${table("digital_twin_usage")} (id,operation_type,source,model,api_requests,input_tokens,output_tokens,total_tokens,cached_tokens,reasoning_tokens,web_search_calls,cost_usd,cost_source,response_id,metadata_json,created_at) VALUES(@id,'decision','digital_twin',@model,@apiRequests,@inputTokens,@outputTokens,@totalTokens,@cachedTokens,@reasoningTokens,@webSearchCalls,@costUsd,@costSource,@responseId,@metadataJson,CURRENT_TIMESTAMP())`,{id:crypto.randomUUID(),model:String(result?.model||stages.at(-1)?.model||""),apiRequests:stages.reduce((a,x)=>a+(Number(x?.apiRequests)||0),0),inputTokens:Number(usage.input_tokens)||0,outputTokens:Number(usage.output_tokens)||0,totalTokens:Number(usage.total_tokens)||0,cachedTokens:Number(usage.input_tokens_details?.cached_tokens)||0,reasoningTokens:Number(usage.output_tokens_details?.reasoning_tokens)||0,webSearchCalls:stages.reduce((a,x)=>a+(Number(x?.webSearchCalls)||0),0),costUsd:b.estimatedTotalCostUsd,costSource:b.estimatedTotalCostUsd==null?null:COST_SOURCE,responseId:String(result?.responseId||""),metadataJson:JSON.stringify({message_count:messageCount,pipeline:result?.pipeline||"hybrid_sol_v1",usage_stages:b.stages})})}catch(e){console.error("Error tracking Digital Twin usage (non-blocking):",{message:e?.message,code:e?.code})}}

async function auditedDecisionChat(req,res){try{const messages=normalizeMessages(req.body?.messages),requestContext=req.body?.context&&typeof req.body.context==="object"?req.body.context:{};if(!messages.length)return res.status(400).json({error:"A decision question is required"});const pc=captureResponse();await getInvestorProfile(req,pc.res);const pr=pc.result();if(pr.statusCode>=400)return res.status(pr.statusCode).json(pr.payload);const profile=pr.payload||{};if(!profile.investor_narrative)return res.status(409).json({error:"Build and confirm the Investor Model before using the Twin chat"});
 const policyIntent=await interpretAndApplyPolicy(messages),currentInvestmentPolicy=await loadCurrentInvestmentPolicy();if(policyIntent.updates.length&&!policyIntent.needsDecision){const result={answer:policyUpdateAnswer(policyIntent.updates),model:policyIntent.usageStage?.model||null,responseId:null,pipeline:"policy_intent_only"};await trackUsage(result,messages.length,[policyIntent.usageStage]);return res.json({...result,currentInvestmentPolicy,investmentPolicyUpdates:policyIntent.updates,usage:policyIntent.usageStage?.usage||null,usageStages:[policyIntent.usageStage],apiRequests:1,tools:{webSearchCalls:0,outputTypes:[]}})}
 const context={...requestContext,currentInvestmentPolicy:{semantics:"current_operational_state_not_investor_preference_or_future_rule",policies:currentInvestmentPolicy}},decisionProfile={...profile,current_operational_state:context.currentInvestmentPolicy},result=await runDecisionPipeline({messages,context,currentProfile:decisionProfile}),combinedStages=mergeUsageStages(policyIntent.usageStage,result?.usageStages||[]);await trackUsage(result,messages.length,combinedStages);try{await persistDecision({messages,result,context:requestContext,currentInvestmentPolicy})}catch(e){console.error("Twin decision persistence failed (non-blocking):",{message:e?.message,code:e?.code})}return res.json({...result,currentInvestmentPolicy,investmentPolicyUpdates:policyIntent.updates,policyIntent:{needsDecision:policyIntent.needsDecision},usageStages:combinedStages,apiRequests:combinedStages.reduce((a,x)=>a+(Number(x?.apiRequests)||0),0)})
}catch(error){console.error("Digital Twin decision failed:",{message:error?.message,code:error?.code,status:error?.response?.status});if(error?.code==="OPENAI_NOT_CONFIGURED")return res.status(503).json({error:"Digital Twin LLM is not configured",code:error.code});return res.status(500).json({error:"Error running Digital Twin decision"})}}
module.exports={auditedDecisionChat};
